// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxuusnodizfpqcrakwkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4dXVzbm9kaXpmcHFjcmFrd2tjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MzM0MjYsImV4cCI6MjA3MTAwOTQyNn0.XgsjinrmAfi9sn37a3htuuQP4ui7YK_iEC1Kfhbc2rU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});